stages:
  - test
  - deploy
  - publish

lint Helm Charts:
  image:
    name: registry.gitlab.com/passbolt/passbolt-ci-docker-images/helm:latest
    entrypoint: ["/bin/sh", "-c"]
  stage: test
  script:
    - helm dependency update
    - helm lint .

test Helm Charts:
  image:
    name: registry.gitlab.com/passbolt/passbolt-ci-docker-images/helm:latest
    entrypoint: ["/bin/sh", "-c"]
  stage: test
  script:
    - helm dependency update
    - helm plugin install https://github.com/helm-unittest/helm-unittest
    - helm unittest --color -d .

publish:
  stage: publish
  image: registry.gitlab.com/passbolt/passbolt-ci-docker-images/helm:latest
  variables:
    REPO_BUCKET: "download.passbolt.com"
    REPO_DIR: "charts"
    CHART_NAME: "passbolt"
  script:
    - |
      export GOOGLE_APPLICATION_CREDENTIALS="$BUCKET_SVC_ACC"
      sh .gitlab-ci/scripts/bin/publishing.sh
  rules:
    - if: "$CI_COMMIT_TAG"
      when: on_success
